# Basic settings
description:  This is personal blog.
baseurl: ""
url: "https://kaia-HSU.github.io" 
twitter_username: LAV_K_V
github_username:  kaia-HSU
include: ['_pages']

# Build settings
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  # 加上vendor
  - vendor

# pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

# Enable comments
comments:
  provider : disqus    # 啟動的留言板服務，這邊就用預設即可
  disqus:
    short_name : kaia-HSU    # 將內容替換成剛剛在disqus上申請的site name
  livefyre:
    site_id: 123
  intensedebate :
    account: 123abc
  facebook:
    appid: 123
    num_posts: 5
    width: 580
    colorscheme: light

# Markdown settings
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
